dist: trusty
sudo: required
language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
  - integration/node_modules
os:
- linux
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
- echo $TRAVIS_BRANCH
- if [ "$TRAVIS_BRANCH" == "master" ]; then echo $TRAVIS_BRANCH; fi
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export CHROME_BIN=chromium-browser
script:
- yarn run lint
- yarn run test
- npm run-script coveralls
- yarn run integration
- yarn run build:demo
- if [ "$TRAVIS_BRANCH" == "master" ]; then node_modules/.bin/gh-pages-travis; fi

env:
  global:
    - DEPLOY_BRANCH="master"
    - SOURCE_DIR="dist"
    - TARGET_BRANCH="gh-pages"
    - SSH_KEY="travis_rsa"
    - GIT_NAME="travis"
    - GIT_EMAIL="andzej.maciusovic@gmail.com"
