dist: trusty
sudo: required
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules
os:
  - linux

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - npm install -g npm@5.3.0

install:
  - npm install

script:
  - npm run lint
  - npm run test
  - npm run integration