name: "CI Test"

on:
  push:
    branches: [DEVOPS-CI-CD-test]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint
        
