name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install dependencies
      run: yarn install
      
    - name: Run lint
      run: yarn run lint
      
    - name: Run tests
      run: yarn run test
      
    - name: Build
      run: yarn run build:demo
