name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Install dependencies
        run: yarn install

      - name: Build ng-select
        run: yarn build
      
      - name: Copy README
        run: cp README.md ./dist/ng-select/

      - name: Semantic release
        run: npx semantic-release
      
      - name: NPM publish
        run: |
          cd dist/ng-select
          cat package.json


